server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:medcheck;MODE=MSSQLServer;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
app:
  disclaimer: "Thông tin chỉ mang tính tham khảo, không thay thế tư vấn của bác sĩ hoặc dược sĩ."
  google-client-id: ${GOOGLE_CLIENT_ID:}
  gemini-api-key: ${GEMINI_API_KEY:}
---
spring:
  config:
    activate:
      on-profile: sqlserver
  datasource:
    url: "jdbc:sqlserver://DESKTOP-401B6OP\\SQLEXPRESSS;databaseName=HTTraCuuThuoc_AI;integratedSecurity=true;encrypt=false;trustServerCertificate=true"
  sql:
    init:
      mode: never
