if col_length('TaiKhoan','Email') is null alter table TaiKhoan add Email varchar(255) null;
if col_length('TaiKhoan','GoogleId') is null alter table TaiKhoan add GoogleId varchar(255) null;
if col_length('TaiKhoan','AnhDaiDien') is null alter table TaiKhoan add AnhDaiDien nvarchar(max) null;
if col_length('TaiKhoan','LoaiDangNhap') is null alter table TaiKhoan add LoaiDangNhap nvarchar(30) null constraint DF_TaiKhoan_LoaiDangNhap default 'LOCAL';
if col_length('Thuoc','TenQuocTe') is null alter table Thuoc add TenQuocTe nvarchar(150) null;
if col_length('Thuoc','CanKeDon') is null alter table Thuoc add CanKeDon bit null constraint DF_Thuoc_CanKeDon default 0;
if col_length('Thuoc','SoDangKy') is null alter table Thuoc add SoDangKy nvarchar(80) null;
if col_length('Thuoc','LoaiThuoc') is null alter table Thuoc add LoaiThuoc nvarchar(100) null;
if col_length('Thuoc','DuongDung') is null alter table Thuoc add DuongDung nvarchar(100) null;
if col_length('Thuoc','HuongDanSuDung') is null alter table Thuoc add HuongDanSuDung nvarchar(max) null;
if col_length('Thuoc','LieuDungThamKhao') is null alter table Thuoc add LieuDungThamKhao nvarchar(max) null;
if col_length('Thuoc','TacDungPhu') is null alter table Thuoc add TacDungPhu nvarchar(max) null;
if col_length('BenhNen','NhomBenh') is null alter table BenhNen add NhomBenh nvarchar(100) null;
if col_length('BenhNen','MaICD') is null alter table BenhNen add MaICD varchar(30) null;
if object_id('Thuoc_TenKhac','U') is null create table Thuoc_TenKhac(MaTenKhac bigint identity primary key,MaThuoc bigint references Thuoc(MaThuoc),TenKhac nvarchar(150) not null);
if object_id('GoiYAI','U') is null create table GoiYAI(MaGoiY bigint identity primary key,MaTaiKhoan bigint references TaiKhoan(MaTaiKhoan),MaChiTietLichSu bigint null references LichSuTraCuu_ChiTiet(MaChiTiet),NoiDungGoc nvarchar(max) not null,NoiDungAI nvarchar(max) not null,LoaiTacVu varchar(50) not null,NguonDuLieu nvarchar(500),TrangThai varchar(20) default 'CHO_DUYET',NguoiDuyet bigint null,NgayTao datetime2 default current_timestamp,NgayDuyet datetime2 null);
if object_id('NhatKyAI','U') is null create table NhatKyAI(MaNhatKy bigint identity primary key,MaTaiKhoan bigint references TaiKhoan(MaTaiKhoan),CauHoi nvarchar(max),CauTraLoi nvarchar(max),LoaiTacVu varchar(50),DuLieuDauVao nvarchar(max),NguonDuLieuSuDung nvarchar(500),MucDoTinCay int,CanhBaoAnToan nvarchar(500),NgayTao datetime2 default current_timestamp);
if col_length('GoiYAI','LyDoXuLy') is null alter table GoiYAI add LyDoXuLy nvarchar(500) null;
if not exists(select 1 from sys.indexes where name='IX_Thuoc_TenThuoc') create index IX_Thuoc_TenThuoc on Thuoc(TenThuoc);
if not exists(select 1 from sys.indexes where name='IX_ThuocTenKhac_TenKhac') create index IX_ThuocTenKhac_TenKhac on Thuoc_TenKhac(TenKhac);
if not exists(select 1 from sys.indexes where name='IX_HoatChat_Ten') create index IX_HoatChat_Ten on HoatChat(TenHoatChat);
if not exists(select 1 from sys.indexes where name='UX_TaiKhoan_Email') create unique index UX_TaiKhoan_Email on TaiKhoan(Email) where Email is not null;
if not exists(select 1 from sys.indexes where name='UX_TaiKhoan_GoogleId') create unique index UX_TaiKhoan_GoogleId on TaiKhoan(GoogleId) where GoogleId is not null;
update t set TenQuocTe=(select top 1 h.TenHoatChat from Thuoc_HoatChat th join HoatChat h on h.MaHoatChat=th.MaHoatChat where th.MaThuoc=t.MaThuoc) from Thuoc t where t.TenQuocTe is null;
if not exists(select 1 from Thuoc_TenKhac) begin
  insert into Thuoc_TenKhac(MaThuoc,TenKhac) select MaThuoc,'Panadol' from Thuoc where TenThuoc like 'Paracetamol%';
  insert into Thuoc_TenKhac(MaThuoc,TenKhac) select MaThuoc,'Advil' from Thuoc where TenThuoc like 'Ibuprofen%';
  insert into Thuoc_TenKhac(MaThuoc,TenKhac) select MaThuoc,'ASA' from Thuoc where TenThuoc like 'Aspirin%';
end;
update GoiYAI set TrangThai=case TrangThai when 'CHO_DUYET' then 'ChoDuyet' when 'DA_DUYET' then 'DaDuyet' when 'TU_CHOI' then 'TuChoi' else TrangThai end;
