drop table if exists NhatKyAI; drop table if exists GoiYAI; drop table if exists LichSuTraCuu_ChiTiet; drop table if exists LichSuTraCuu;
drop table if exists TuongTacHoatChat; drop table if exists CanhBaoDiUng_HoatChat; drop table if exists QuyTacCanhBao;
drop table if exists BenhNhan_ThuocDangDung; drop table if exists BenhNhan_DiUng; drop table if exists BenhNhan_BenhNen;
drop table if exists Thuoc_HoatChat; drop table if exists Thuoc_TenKhac; drop table if exists HoatChat; drop table if exists Thuoc; drop table if exists DiUng; drop table if exists BenhNen; drop table if exists BenhNhan; drop table if exists AuditLog; drop table if exists TaiKhoan;

create table TaiKhoan(MaTaiKhoan bigint identity primary key, TenDangNhap varchar(255) unique not null, Email varchar(255), MatKhauHash varchar(100), HoTen nvarchar(100), VaiTro varchar(20) not null, TrangThai bit default 1, GoogleId varchar(255), AnhDaiDien nvarchar(max), LoaiDangNhap nvarchar(30) default 'LOCAL', NgayTao datetime2 default current_timestamp);
create table BenhNhan(MaBenhNhan bigint identity primary key, MaTaiKhoan bigint unique references TaiKhoan(MaTaiKhoan), HoTen nvarchar(100), NgaySinh date, GioiTinh nvarchar(20), ChieuCao decimal(5,2), CanNang decimal(5,2), NhomMau varchar(5), DiaChi nvarchar(250), GhiChu nvarchar(500));
create table BenhNen(MaBenhNen bigint identity primary key, TenBenh nvarchar(150) not null, TenThongDung nvarchar(150), NhomBenh nvarchar(100), MaICD varchar(30), MoTa nvarchar(500), TrangThai bit default 1);
create table DiUng(MaDiUng bigint identity primary key, TenDiUng nvarchar(150) not null, MoTa nvarchar(500), TrangThai bit default 1);
create table Thuoc(MaThuoc bigint identity primary key, TenThuoc nvarchar(150) not null, TenQuocTe nvarchar(150), SoDangKy nvarchar(80), LoaiThuoc nvarchar(100), DangBaoChe nvarchar(100), DuongDung nvarchar(100), HamLuong nvarchar(80), NhaSanXuat nvarchar(150), MoTa nvarchar(1000), HuongDanSuDung nvarchar(max), LieuDungThamKhao nvarchar(max), TacDungPhu nvarchar(max), CanKeDon bit default 0, TrangThai bit default 1);
create table Thuoc_TenKhac(MaTenKhac bigint identity primary key, MaThuoc bigint references Thuoc(MaThuoc), TenKhac nvarchar(150) not null);
create table HoatChat(MaHoatChat bigint identity primary key, TenHoatChat nvarchar(150) not null, MoTa nvarchar(500), TrangThai bit default 1);
create table Thuoc_HoatChat(MaThuoc bigint references Thuoc(MaThuoc), MaHoatChat bigint references HoatChat(MaHoatChat), HamLuong nvarchar(80), primary key(MaThuoc,MaHoatChat));
create table BenhNhan_BenhNen(MaBenhNhan bigint references BenhNhan(MaBenhNhan), MaBenhNen bigint references BenhNen(MaBenhNen), GhiChu nvarchar(300), primary key(MaBenhNhan,MaBenhNen));
create table BenhNhan_DiUng(MaBenhNhan bigint references BenhNhan(MaBenhNhan), MaDiUng bigint references DiUng(MaDiUng), MucDo nvarchar(30), primary key(MaBenhNhan,MaDiUng));
create table BenhNhan_ThuocDangDung(MaSuDung bigint identity primary key, MaBenhNhan bigint references BenhNhan(MaBenhNhan), MaThuoc bigint references Thuoc(MaThuoc), LieuDung nvarchar(100), TanSuat nvarchar(100));
create table QuyTacCanhBao(MaQuyTac bigint identity primary key, MaHoatChat bigint references HoatChat(MaHoatChat), MaBenhNen bigint references BenhNen(MaBenhNen), MucDo varchar(30), NoiDung nvarchar(1000), KhuyenNghi nvarchar(1000), Nguon nvarchar(500), TrangThai varchar(30) default 'ChoDuyet');
create table CanhBaoDiUng_HoatChat(MaDiUng bigint references DiUng(MaDiUng), MaHoatChat bigint references HoatChat(MaHoatChat), MucDo varchar(30), NoiDung nvarchar(500), primary key(MaDiUng,MaHoatChat));
create table TuongTacHoatChat(MaTuongTac bigint identity primary key, MaHoatChat1 bigint references HoatChat(MaHoatChat), MaHoatChat2 bigint references HoatChat(MaHoatChat), MucDo varchar(30), HauQua nvarchar(700), KhuyenNghi nvarchar(700));
create table LichSuTraCuu(MaLichSu bigint identity primary key, MaBenhNhan bigint references BenhNhan(MaBenhNhan), MaThuoc bigint references Thuoc(MaThuoc), ThoiGian datetime2 default current_timestamp, MucDoCaoNhat varchar(30));
create table LichSuTraCuu_ChiTiet(MaChiTiet bigint identity primary key, MaLichSu bigint references LichSuTraCuu(MaLichSu), LoaiCanhBao nvarchar(50), MucDo varchar(30), NoiDung nvarchar(1000));
create table AuditLog(MaAudit bigint identity primary key, MaTaiKhoan bigint, HanhDong nvarchar(100), DoiTuong nvarchar(100), ChiTiet nvarchar(1000), ThoiGian datetime2 default current_timestamp);
create table GoiYAI(MaGoiY bigint identity primary key, MaTaiKhoan bigint references TaiKhoan(MaTaiKhoan), MaChiTietLichSu bigint null references LichSuTraCuu_ChiTiet(MaChiTiet), NoiDungGoc nvarchar(max) not null, NoiDungAI nvarchar(max) not null, LoaiTacVu varchar(50) not null, NguonDuLieu nvarchar(500), TrangThai varchar(20) default 'ChoDuyet', NguoiDuyet bigint null, LyDoXuLy nvarchar(500), NgayTao datetime2 default current_timestamp, NgayDuyet datetime2 null);
create table NhatKyAI(MaNhatKy bigint identity primary key, MaTaiKhoan bigint references TaiKhoan(MaTaiKhoan), CauHoi nvarchar(max), CauTraLoi nvarchar(max), LoaiTacVu varchar(50), DuLieuDauVao nvarchar(max), NguonDuLieuSuDung nvarchar(500), MucDoTinCay int, CanhBaoAnToan nvarchar(500), NgayTao datetime2 default current_timestamp);
create index IX_Thuoc_TenThuoc on Thuoc(TenThuoc);
create index IX_ThuocTenKhac_TenKhac on Thuoc_TenKhac(TenKhac);
create index IX_HoatChat_Ten on HoatChat(TenHoatChat);
create index IX_GoiYAI_TrangThai on GoiYAI(TrangThai,NgayTao);
create index IX_NhatKyAI_NgayTao on NhatKyAI(NgayTao);
